# This workflow runs tests and builds a snapshot package
name: Maven Package

on:
  push:
    branches:
    - develop

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  M2_SETTINGS: https://raw.githubusercontent.com/lukecmstevens/packages/master/.m2/settings.xml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Download .m2 settings
      run: curl $M2_SETTINGS -O

    - name: Build with Maven
      run: mvn -B package -s settings.xml --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s settings.xml
